name: Vercel

on:
  push:
  pull_request:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - name: test secrets
      - run: |
         - vercel_token="${{ secrets.VERCEL_TOKEN }}"
         - echo "vercel_token length: ${#auth_token}"

         - github_token="${{ secrets.GITHUB_TOKEN }}"
         - echo "github_token length: ${#GITHUB_TOKEN}"

         - vercel_pid="${{ secrets.VERCEL_PROJECT_ID }}"
         - echo "vercel_pid length: ${#GITHUB_TOKEN}"


      - uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          CREATE_COMMENT: true
          ATTACH_COMMIT_METADATA: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: ${{ github.ref == 'refs/heads/main' }}
          
