name: Vercel

on:
  push:
  pull_request:

jobs:
  vercel_deploy:
    name: Vercel Deploy
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      VAULT_ID: ${{ secrets.VAULT_ID }}
    permissions:
      contents: read
      deployments: write
      statuses: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          CREATE_COMMENT: true
          ATTACH_COMMIT_METADATA: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: ${{ github.ref == 'refs/heads/main' }}
          
